config/routes.rb
Rails.application.routes.draw do
  root to: 'maps#index'
  resources :maps
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  validates :file, presence: true
  validates :name, presence: true, uniqueness: true

  has_one_attached :file
  has_one :preview
  has_many :taggings
  has_many :tags, through: :taggings
  
  def self.search(searchterm)
    if searchterm != ""
      where name: searchterm
    else
      all
    end
  end

  def self.find_by_tag(tagname)
    tags = Tag.where 'name LIKE ?', "%#{tagname}%"
    if tags != []
      maps = Set.new
      tags.each do |t|
        t.maps.each { |m| maps << m }
      end
      return maps
    else
      return []
    end
    # return tag.maps if tags
    # []
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  def tag_list_add(tag)
    self.tags << Tag.where(name: tag).first_or_create!
  end

end

app/models/preview.rb
class Preview < ApplicationRecord
  has_one_attached :image
  belongs_to :map
  enum status: [:pending, :done, :error]
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :maps, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :map
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = if params.has_key?(:search)&& params[:search] != ""
              # Map.search params[:search]
               Map.find_by_tag params[:search]
            else
               Map.all
            end
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    result = CreateMapService.call(map_params)
    @map = result[:obj]
    
    respond_to do |format|
      if result[:succes]
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    DestroyMapService.call(@map)
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:name, :file, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AosMapDirectory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon_w.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/_form.html.erb
<%= form_with(model: map, local: true) do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
        <% map.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

   <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>  

 <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tag_list, value: @map.tag_list || nil %>
  </div>  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maps</h1>

<div>
  <p>
  <%= form_tag maps_path, method: 'get' do %>
  <%= text_field_tag :search, params[:search] %> 
  <%= submit_tag "Search", name: nil %>
  </p>
<% end %>
</div>

<table class="primary">
  <thead>
    <tr>
      <b><%= @maps == [] ? 'No maps found' : 'Maps' %></b>
    </tr>
  </thead>
	<tbody>
    <% @maps.each do |map| %>
		<tr class="maprow">
			<td class="maprow">
				<table class="innert">
					<tbody>
						<tr>
							<td>
								
      <%= map.name %>

							</td>
						</tr>
						<tr>
							<td>
								          <%= link_to 'Show', map %>
          <%= link_to 'Edit', edit_map_path(map) %>
          <%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
			<td class="maprow">
				<%= image_tag map.preview.image.variant(resize_to_limit: [400, 400]) %>
			</td>
    </tr>
  <% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @map.name %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @map.file.filename %>
  <p>
  <%= @map.preview.inspect %>
  </p>
  <%= image_tag @map.preview.image.variant(resize_to_limit: [600, 600]) if @map.preview.done? %>
  <p>
  <strong>size:</strong>
  <%= "#{@map.file.byte_size} bytes" %>
  </p>
  <p><strong>Tags</strong>
  <% @map.tags.each do |tag| %>
    <div><%= link_to("#{tag.name}", controller: "maps", search: "#{tag.name}") %></div>
  <% end %>
  </p>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %> |
<%= link_to 'Destroy', @map, method: :delete, data: { confirm: 'Are you sure?' } %>